version: '3.7'

services:
    development:
        stdin_open: true # docker run -i
        tty: true # docker run -t
        container_name: relectric-ui-container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
