name: 'Pull Request Labeler and Assigner'
on: [pull_request]

jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@main
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
            - uses: TimonVS/pr-labeler-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    assign:
        runs-on: ubuntu-latest
        steps:
            - uses: kentaro-m/auto-assign-action@v1.1.2
