name: Run checks on PR
'on': pull_request
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: Prettify code
              uses: creyD/prettier_action@v3.1
              with:
                  prettier_options: --write .
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Yarn install
              run: yarn install
            - name: ESLint checker
              run: yarn run eslint ./src --ext .js,.jsx,.ts,.tsx
            - name: Build
              run: yarn run build
