name: Run checks on PR
'on': pull_request
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: Yarn install
              run: yarn install
            - name: ESLint checker
              run: yarn run eslint ./src --ext .js,.jsx,.ts,.tsx
            - name: Build
              run: yarn run build
